services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ehsanap
      POSTGRES_PASSWORD: ehsan123
      PGDATA: /data/postgres
    volumes:
      - db_data:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  ehsanap-api:
    container_name: ehsanap-api
    image: ehsanap/ehsanap-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  db_data:
