CREATE TABLE customer(
  ID BIGSERIAL PRIMARY KEY,
  NAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL UNIQUE,
  PASSWORD TEXT  NOT NULL,
  AGE INT NOT NULL,
  GENDER TEXT NOT NULL
);

CREATE SEQUENCE customer_id_sequence
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO MINVALUE
    CACHE 1;