server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: ehsanap
    password: ehsan123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
